<?php
/**
 * @file
 * Module used to add a datastream to a pdf
 **/

/**
 * Implements hook_menu().
 */
function islandora_add_datastream_menu() {
  drupal_set_message("menu stuff");
  $items['admin/islandora/tools/add_datastream'] = array(
    'title' => 'Add a Datastream',
    'description' => 'Add datastreams in PDF content model',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_add_datastream_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}



/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_add_datastream_islandora_ingest_steps(array &$form_state) {
  $steps = array();

  module_load_include('inc', 'islandora', 'includes/ingest.form');
  module_load_include('inc', 'islandora', 'includes/utilities');
  $shared_storage = islandora_ingest_form_get_shared_storage($form_state);

  $datastreams = islandora_get_datastreams_requirements_from_models($shared_storage['models']);

  return $steps;
}


/**
 * Implements hook_islandora_ingest_steps_alter().
 */


function islandora_add_datastream_islandora_ingest_steps_alter(array &$steps, array &$form_state) {


// alter the ingest steps to add a form.

drupal_set_message("ingest steps alter troubleshooting");

  if (isset($steps['xml_form_builder_metadata_step'])) {
    $association = isset($steps['xml_form_builder_metadata_step']['args'][0]) ? $steps['xml_form_builder_metadata_step']['args'][0] : NULL;
    if (isset($association['dsid']) && $association['dsid'] == 'MODS') {

      // $selected_collection_name = isset($form_state['islandora']['shared_storage']['parent']) ? $form_state['islandora']['shared_storage']['parent'] : NULL;
      // $selected_urls = get_license_deposit_url($selected_collection_name);
      $selected_urls = 1;
      if($selected_urls > 0) {
        drupal_set_message("metadata steps yo");
        $steps['islandora_add_datastream_form'] = array(
          'type' => 'form',
          'form_id' => 'islandora_add_datastream_form',
          'weight' => -10,
          // 'args' => array($selected_urls),
          'file' => 'includes/deposit_form.inc',
          'module' => 'islandora_add_datastream',
        );
      }
    }
  }
}

/**
 * Implements hook_islandora_edit_datastream_registry().
 */
function islandora_oralhistories_islandora_edit_datastream_registry(AbstractObject $object, AbstractDatastream $datastream) {
  if (strtoupper($datastream->id) == 'LICENSE') {
    return array(
      array(
        'name' => t('Islandora LICENSE EDIT FORM'),
        'url' => "islandora/object/{$object->id}/edit_form/{$datastream->id}",
      ),
    );
  }
}
